apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dshuttle-fuse-2
  labels:
    app: dshuttle-fuse-2
spec:
  selector:
    matchLabels:
      app: dshuttle-fuse-2
  template:
    metadata:
      labels:
        app: dshuttle-fuse-2
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pai-worker
                operator: In
                values:
                - "true"
      initContainers:
      - name: umount
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        image: dshuttle/dshuttle-fuse:latest
        command: ["/bin/sh"]
        args: ["-c", "fusermount -u /mnt/fuse2 || true"]
        volumeMounts:
        - name: dshuttle-fuse-device
          mountPath: /dev/fuse
        - name: dshuttle-fuse-parent
          mountPath: /mnt
          mountPropagation: Bidirectional
      containers:
        - name: dshuttle-fuse
          image: dshuttle/dshuttle-fuse:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 6
              memory: 8G
            requests:
              cpu: 0.5 
              memory: 1G
          command: ["/entrypoint.sh"]
          args:
            - fuse
            - --fuse-opts=allow_other
          env:
          - name: ALLUXIO_CLIENT_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: ALLUXIO_CLIENT_JAVA_OPTS
            value: " -Dalluxio.user.hostname=$(ALLUXIO_CLIENT_HOSTNAME) -Dalluxio.worker.hostname=$(ALLUXIO_CLIENT_HOSTNAME)  -XX:MaxDirectMemorySize=2g "
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          lifecycle:
            preStop:
              exec:
                command: ["/opt/alluxio/integration/fuse/bin/alluxio-fuse", "unmount", "/alluxio-fuse"]
          envFrom:
          - configMapRef:
              name: dshuttle-config
          volumeMounts:
            - name: dshuttle-fuse-device
              mountPath: /dev/fuse
            - name: dshuttle-fuse-mount
              mountPath: /alluxio-fuse
              mountPropagation: Bidirectional
            - name: dshuttle-domain
              mountPath: /opt/domain
            - name: fuse-logs
              mountPath: /opt/alluxio/logs
      restartPolicy: Always
      volumes:
        - name: dshuttle-fuse-device
          hostPath:
            path: /dev/fuse
            type: File
        - name: dshuttle-fuse-mount
          hostPath:
            path: /mnt/dshuttle/fuse2
            type: DirectoryOrCreate
        - name: dshuttle-fuse-parent
          hostPath:
            path: /mnt/dshuttle
        - name: dshuttle-domain
          hostPath:
            path: /tmp/alluxio-domain
            type: "Directory"
        - name: fuse-logs
          hostPath:
            path: /var/log/dshuttle
            type: DirectoryOrCreate
